const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const userSchema = new mongoose.Schema({
  // ========== COMMON FIELDS (ALL ROLES) ==========
  userId: {
    type: String,
    required: [true, 'User ID is required'],
    unique: true,
    trim: true
  },
  email: {
    type: String,
    required: [true, 'Email is required'],
    unique: true,
    lowercase: true,
    trim: true,
    match: [/^\w+([.-]?\w+)*@\w+([.-]?\w+)*(\.\w{2,3})+$/, 'Please provide a valid email']
  },
  password: {
    type: String,
    required: [true, 'Password is required'],
    minlength: [6, 'Password must be at least 6 characters'],
    select: false
  },
  role: {
    type: String,
    required: [true, 'Role is required'],
    enum: {
      values: [
        'super_admin',
        'admin', 
        'principal',
        'academic_dean',      
        'hod',
        'faculty',
        'student',
        'parent',
        'accountant',
        'librarian',
        'placement_officer'
      ],
      message: '{VALUE} is not a valid role'
    }
  },
  firstName: {
    type: String,
    required: [true, 'First name is required'],
    trim: true
  },
  lastName: {
    type: String,
    required: [true, 'Last name is required'],
    trim: true
  },
  phone: {
    type: String,
    required: [true, 'Phone number is required'],
    trim: true
  },
  dateOfBirth: {
    type: Date
  },
  gender: {
    type: String,
    enum: ['Male', 'Female', 'Other']
  },
  address: {
    street: String,
    city: String,
    state: String,
    zipCode: String,
    country: String
  },
  profileImage: {
    type: String,
    default: ''
  },
  status: {
    type: String,
    enum: ['Active', 'Inactive', 'Suspended'],
    default: 'Active'
  },
  
  // ========== ROLE-SPECIFIC FIELDS ==========
  
  // STUDENT INFO
  studentInfo: {
    prn: String, // Permanent Registration Number
    department: {
      type: String,
      enum: ['CSE', 'ECE', 'MECH', 'CIVIL', 'IT', 'EEE']
    },
    classYear: {
      type: String,
      enum: ['FY', 'SY', 'TY']
    },
    division: {
      type: String,
      uppercase: true
    },
    rollNo: Number,
    semester: {
      type: Number,
      min: 1,
      max: 8
    },
    enrollmentDate: Date,
    parentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    }
  },
  
  // FACULTY INFO
  facultyInfo: {
    employeeId: String,
    departmentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Department'
    },
    department: String, // denormalized for easy access
    designation: {
      type: String,
      enum: ['Professor', 'Associate Professor', 'Assistant Professor', 'Lecturer']
    },
    qualification: String,
    experience: Number,
    subjects: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Subject'
    }],
    joiningDate: Date
  },
  
// HOD INFO
hodInfo: {
  departmentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Department'
  },
  department: String,
  employeeId: String,
  appointmentDate: Date,
  selectedCourses: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Course'
  }]
},
  
  // PARENT INFO
  parentInfo: {
    occupation: String,
    children: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User'
    }]
  },
  
  // ACCOUNTANT INFO
  accountantInfo: {
    employeeId: String,
    joiningDate: Date,
    department: String
  },
  
  // LIBRARIAN INFO
  librarianInfo: {
    employeeId: String,
    joiningDate: Date
  },
  
  // PLACEMENT OFFICER INFO
  placementInfo: {
    employeeId: String,
    joiningDate: Date,
    department: String
  },
  
  // ADMIN/PRINCIPAL INFO (minimal, mostly use common fields)
  adminInfo: {
    employeeId: String,
    joiningDate: Date
  },

    // ...existing fields
  isApproved: { type: Boolean, default: false },         // admin confirmed
  requestedAt: { type: Date },
  approvedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },

  // ID issuance flow
  employeeIdIssued: { type: String, default: '' },       // ID generated by admin (but not yet verified by user)
  employeeIdVerified: { type: Boolean, default: false }, // becomes true when the user inputs the same ID
  employeeIdVerifiedAt: { type: Date },
  employeeIdIssuedAt: { type: Date },

  // e-mail tracking (optional)
  employeeIdEmailSentAt: { type: Date },

  // convenience for filtering
  requestedRole: { type: String },
  requestedDepartment: { type: String }
  
}, {
  timestamps: true
});

// ========== MIDDLEWARE ==========

// Hash password before saving
userSchema.pre('save', async function(next) {
  if (!this.isModified('password')) {
    return next();
  }
  
  const salt = await bcrypt.genSalt(12);
  this.password = await bcrypt.hash(this.password, salt);
  next();
});

// ========== METHODS ==========

// Compare entered password with hashed password
userSchema.methods.matchPassword = async function(enteredPassword) {
  return await bcrypt.compare(enteredPassword, this.password);
};

// Get user's full name
userSchema.methods.getFullName = function() {
  return `${this.firstName} ${this.lastName}`;
};

module.exports = mongoose.model('User', userSchema);
